version = 1

[merge]
priority_merge_label = "high priority"

[merge.automerge_dependencies]
versions = [ "minor", "patch" ]
usernames = [ "renovate" ]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
include_coauthors = true
include_pull_request_author = true
