image: nixos/unstable
sources:
  - https://git.sr.ht/~yuiyukihira/featurize
secrets:
  - "fly-token"
packages:
  - nixos.docker
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - build: |
      cd ~/featurize
      nix build .#auth
  - check: |
      cd ~/featurize
      nix flake check
  - check-for-tag: |
      if [ $(git tag --points-at HEAD | wc -l) -eq 0 ]; then \
      cd ~/featurize
        echo "not a release, stopping"; \
        complete-build; \
      fi
  - setup-docker: |
      . ~/featurize/ci/setup-docker.sh
  - deploy: |
      cd ~/featurize
      nix develop --command deploy all
