app = "featurize-auth"
primary_region = "lhr"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[build]
image = "registry.fly.io/featurize-auth:0.1.0"

[env]
KRATOS_DOMAIN = "https://kratos.dragnof.pro"
PORT = "8080"
RUST_BACKTRACE = "1"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
