name: Check & Deploy
on:
  push:
    branches:
      - main
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check
  deploy:
    needs:
      - check
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Login to Fly.io docker reg
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Deploy to Fly.io
        run: nix develop .#ci --command deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
