name: PR
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
      - name: Check
        run: nix flake check
  conform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
      - name: Conform
        run:
          nix develop .#ci --command conform enforce --revision-range ${{
          github.event.pull_request.head.sha }}~${{
          github.event.pull_request.commits }}..${{
          github.event.pull_request.head.sha }}
      - name: Treefmt
        run: nix develop .#ci --command treefmt -c --fail-on-change
